Aplikacja-do-nauki-Pythona/apka_wstepna/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('chapters.urls', 'chapters'), namespace='chapters')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('icons/python.ico'))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplikacja-do-nauki-Pythona/chapters/urls.py
"""Defines URL patterns for chapters."""


from django.urls import path


from . import views

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Literatura
    path('literatura/', views.literatura, name='literatura'),

    # Kodowanie
    path('kodowanie/', views.kodowanie, name='kodowanie'),

    # Pomoc
    path('pomoc/', views.pomoc, name='pomoc'),
    path('pomoc/<int:chapter_id>/', views.pomoc_chapter, name='pomoc_chapter'),

    # Show all chapters and topics
    path('chapters/', views.chapters, name='chapters'),
    path('chapters/<int:chapter_id>/', views.topic, name='topic'),

    # Approach for the topic
    path('topic/<int:topic_id>', views.approach, name='approach'),
]

Aplikacja-do-nauki-Pythona/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [
    # Login page
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    # Logout page
    path('logout/', views.logout_view, name='logout'),
    # Register page
    path('register/', views.register, name='register'),
]

Aplikacja-do-nauki-Pythona/chapters/models.py
from django.db import models
from django.contrib.auth.models import User


class Chapter(models.Model):
    """Chapters the user is learning about"""
    name = models.CharField(max_length=200)
    text = models.TextField()
    pomoc_text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.name

    def get_chapter_points(self):
        topics = Topic.objects.filter(chapter_id=self.id)
        ch_points = 0
        for topic in topics:
            ch_points += topic.points
        return ch_points

    def user_chapter_points(self, user):
        topics = Topic.objects.filter(chapter_id=self.id)
        user_points = 0
        for topic in topics:
            approaches = topic.userapproach_set.all()
            for approach in approaches:
                if approach.user == user:
                    user_points += approach.points_earned
        return user_points


class Topic(models.Model):
    """Topic included in Chapters"""
    chapter = models.ForeignKey(Chapter, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=200)
    text = models.TextField()
    code_text = models.TextField(default="")
    approach = models.TextField(default='print("Hello World!")')
    points = models.IntegerField(default=3)
    date_added = models.DateTimeField(auto_now_add=True)
    output = models.TextField(default='Hello World!')

    def __str__(self):
        return self.name

    def user_topic_points(self, user):
        approaches = self.userapproach_set.all()
        user_topic_points = 0
        for approach in approaches:
            if approach.user == user:
                user_topic_points = approach.points_earned
        return user_topic_points


class UserApproach(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    user_approach = models.TextField(default='')
    points_awarded = models.BooleanField(default=False)
    points_earned = models.IntegerField(default=0)


class Code(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test_code = models.TextField(default='print("Hello World!")')

Aplikacja-do-nauki-Pythona/chapters/forms.py
from django import forms

from .models import UserApproach, Code



class ApproachForm(forms.ModelForm):
    class Meta:

        model = UserApproach
        fields = ['user_approach']
        labels = {'user_approach': ''}
        widgets = {'user_approach': forms.Textarea(attrs={
            'cols': 100,
            'id': 'editor',
        })}


class UserCode(forms.ModelForm):
    class Meta:
        model = Code
        fields = ['test_code']
        labels = {'test_code': ''}
        widgets = {'test_code': forms.Textarea(attrs={
            'cols': 100,
            'id': 'code',
        })}

Aplikacja-do-nauki-Pythona/chapters/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404

from .models import Chapter, Topic, UserApproach, Code
from users.models import Profile

from .forms import ApproachForm, UserCode
from .functions import exec_user_input

import operator


# Funkcja do "Kontunuuj naaukę"
def last_topic(approaches):
    last_approach = approaches[-1]
    last_topic_id = last_approach.topic.id
    return last_topic_id


def index(request):
    u = User.objects.all()
    users = sorted(u, key=operator.attrgetter('profile.points'), reverse=True)
    if request.user.is_authenticated:
        approaches = UserApproach.objects.filter(user=request.user)
        approaches = sorted(approaches, key=operator.attrgetter('topic.id'))
        if len(approaches) > 0:
            last_topic_id = last_topic(approaches)
        else:
            last_topic_id = 1
    else:
        last_topic_id = 1
    context = {'users': users, 'last_topic_id': last_topic_id}
    return render(request, 'chapters/index.html', context)


@login_required
def chapters(request):
    """Show all chapters"""
    chapters = Chapter.objects.order_by('id')
    context = {'chapters': chapters}
    return render(request, 'chapters/chapters.html', context)


@login_required
def topic(request, chapter_id):
    """Show all topics of chapter"""
    chapter = get_object_or_404(Chapter, id=chapter_id)
    topics = chapter.topic_set.all()
    context = {'chapter': chapter, 'topics': topics}
    return render(request, 'chapters/topic.html', context)


@login_required
def approach(request, topic_id):
    """Add a new approach for topic"""
    topic = Topic.objects.get(id=topic_id)

    approach, _ = UserApproach.objects.get_or_create(user=request.user, topic=topic)
    res = exec_user_input(approach.user_approach)

    if request.method != 'POST':
        if approach.user_approach:
            form = ApproachForm(instance=approach)
        else:
            approach.user_approach = topic.approach
            form = ApproachForm(instance=approach)
    else:
        form = ApproachForm(instance=approach, data=request.POST)
        points_f = Profile.objects.get(user=request.user)
        if form.is_valid():
            form.save()
        user_input = request.POST['user_approach']
        res = exec_user_input(user_input)
        if type(res) == str:
            res_check = ''.join(res.split())
            topic_check = ''.join(topic.output.split())
            if form.is_valid():
                if res_check == topic_check:
                    messages.success(request, 'Correct!')
                    if not approach.points_awarded:
                        points_f.points += topic.points
                        approach.points_earned = topic.points
                        approach.points_awarded = True
                        points_f.save()
                        approach.points_earned = topic.points
                        approach.points_awarded = True
                        approach.save()

                return HttpResponseRedirect(reverse('chapters:approach', args=[topic.id]))
    context = {'topic': topic, 'form': form, 'res': res, 'approach': approach}
    return render(request, 'chapters/approach.html', context)


def literatura(request):
    """Information about books."""
    return render(request, 'chapters/literatura.html')

@login_required
def pomoc(request):
    """Information about books."""
    chapters = Chapter.objects.order_by('id')
    context = {'chapters': chapters}
    return render(request, 'chapters/pomoc_list.html', context)


@login_required
def pomoc_chapter(request, chapter_id):
    """
        Auxliary info for every chapter.
    """
    chapter = get_object_or_404(Chapter, id=chapter_id)
    context = {
        "chapter": chapter
        }
    return render(request, 'chapters/pomoc.html', context)


@login_required
def kodowanie(request):
    """Code mirror for user"""
    code, _ = Code.objects.get_or_create(user=request.user)
    res = exec_user_input(code.test_code)

    if request.method != 'POST':
        form = UserCode(instance=code)
    else:
        form = UserCode(instance=code, data=request.POST)
        code_input = request.POST['test_code']
        res = exec_user_input(code_input)
        if form.is_valid():
            new_code = form.save(commit=False)
            new_code.user = request.user
            new_code.save()
            return HttpResponseRedirect(reverse('chapters:kodowanie'))

    context = {'form': form, 'res': res}
    return render(request, 'chapters/kodowanie.html', context)

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/approach.html
{% extends 'chapters/topic.html' %}
{% load  chapters_extras %}


{% block header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Początek</a></li>
    <li class="breadcrumb-item">
      <a href="{% url 'chapters:chapters' %}">Rozdziały</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'chapters:topic' topic.chapter.id %}">{{ topic.chapter }}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{{ topic }}</li>
  </ol>
</nav>
<div class="text-center mb-2">
  <h2>{{ topic }}</h2>
</div>
{% endblock header %}

{% block content %}
<div class="d-flex flex-wrap justify-content-center">
  <div class="approach_task">
    <div class="border-bottom">
      <div class="d-flex justify-content-center">
      <a id="task-button" class="btn btn-light px-5">Zadanie</a>
        <a id="console-button" class="btn btn-light px-5">Konsola</a>
      </div>
    </div>
    <div>
      <div id="task">
        <div style="padding: 5px; margin: 5px">{{ topic.text|linebreaks }}</div>
        <div class="terminal mx-auto" >
          {% autoescape off %}
            {{ topic.code_text|linebreaks }}
          {% endautoescape %}
        </div>
      </div>

    <div id="console" class="terminal" style="display: none;">
      {% if res %}
          {{ res|linebreaks }}
        </div>
      {% else %}
        <p>Tutaj pojawi się rezultat....</p>
      </div>
      {% endif %}

    </div>
  </div>
  <div>
    <form action="{% url 'chapters:approach' topic.id %}" method="post">
        <div style="font-size: 14px; opacity: 0.85;" class="approach_code_pomoc">
        {% csrf_token %}
        {{ form.as_p }}
          <script>
                var editor = CodeMirror.fromTextArea(document.getElementById('editor'), {
                      mode: "python",
                      theme: "erlang-dark",
                      lineNumbers: true,
                      autoCloseBrackets: true,
                      lineWrapping: true,
                  });
                editor.setSize(null, 500);
            </script>
        </div>

        <button name="submit" id="code-run-button" class="btn btn-info float-left">Uruchom</button>
    </form>
      {% if approach.points_awarded %}
          <a href="{% get_next_topic topic.id %}">
              <button id="next_topic_button_id" class="btn btn-warning float-left ml-1" >Następny temat</button>
          </a>
      {% endif %}
    </div>
</div>


<script>
  $(document).ready(function () {
    $("#code-run-button").on("click", () => {
      localStorage.setItem("layout-item", "console")
    })

    $("#task-button").on("click", () => {
      localStorage.setItem("layout-item", "task")
        $("#console").hide()
        $("#task").show()
    })

    $("#console-button").on("click", () => {
      localStorage.setItem("layout-item", "console")
        $("#task").hide()
        $("#console").show()
    })

    $("#next_topic_button_id").on("click", () => {
      localStorage.setItem("layout-item", "task")
    })

    itemToClick = localStorage.getItem("layout-item")
    $("#" + itemToClick + "-button").click()
    }
  )
</script>
{% endblock content %}

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/baza.html
<!DOCTYPE HTML>
{% load static %}
{% load bootstrap3 %}
{% load bootstrap4 %}

<html lang="pl">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@1,300&display=swap" rel="stylesheet">


    <!-- Code Mirror -->
    <script type="text/javascript" src="{% static 'codemirror/lib/codemirror.js' %}"></script>
    <link href="{% static 'codemirror/lib/codemirror.css' %}" rel="stylesheet">
    <script src="{% static 'codemirror/mode/python/python.js' %}"></script>
    <script src="{% static 'codemirror/addon/edit/closebrackets.js' %}"></script>
    <link href="{% static 'codemirror/theme/erlang-dark.css' %}" rel="stylesheet">


    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <title>Aplikacja do nauki Pythona</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
{% include "chapters/navbar.html" %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>{{ message }}</strong>
      <button type="button" class="close"  aria-label="Close">
        <span aria-hidden="true" data-dismiss="alert">&times;</span>
      </button>
    </div>
    {% endfor %}
{% endif %}

{% block header %}{% endblock header %}
{% block content %}{% endblock content %}

</body>
</html>

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/chapters.html
<html lang="pl">
{% extends "chapters/baza.html" %}
{% load  chapters_extras %}
{% load  static %}

{% block header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'chapters:index' %}">Początek</a></li>
    <li class="breadcrumb-item active" aria-current="page">Rozdziały</li>
  </ol>
</nav>
<div class="text-center mb-2">
  <h2>Rozdziały:</h2>
</div>
{% endblock header %}

{% block content %}
<div class="d-flex flex-wrap justify-content-center">
  {% for chapter in chapters %}
    <div class="card border-{% get_theme forloop.counter0 %} mx-2 my-2 float-left"
      style="width: 25rem; height: 25rem;">
      <div class="card-header">{{ chapter.name }}</div>
      <div class="card-body">
        <p class="card-text">{{ chapter.text }}.</p>
        <div class="progress">
          <div class="progress-bar bg-success" role="progressbar" style="width: {% calc_chapter_progres user chapter %}%" 
          aria-valuenow="{% calc_chapter_progres user chapter %}" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <a href="{% url 'chapters:topic' chapter.id %}"
        class="btn btn-outline-{% get_theme forloop.counter0 %} mt-5">
          {% get_chapter_points_tag chapter user %} / {{ chapter.get_chapter_points }}</a>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}
</html>

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/index.html
{% extends "chapters/baza.html" %}
{% load static %}

{% block header %}
<div id="carouselExampleControls" class="carousel slide mx-auto" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block mx-auto" style="max-width:100%" height="400" src="{% static 'img/learn_python_slide.png' %}"
      alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block mx-auto" style="max-width:100%" height="400" src="{% static 'img/sign_python_slide.png' %}"
      alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block mx-auto" style="max-width:100%" height="400" src="{% static 'img/code_python_slide.png' %}"
      alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% endblock header %}


{% block content %}
<div class="index_content">
  <div class="text-center">
    {% if user.is_authenticated %}
      {% if user.profile.points == 0 %}
        <h2><a href="{% url 'chapters:approach' 1 %}">Zacznij naukę</a> od zaraz.</h2>
      {% else %}
        <h2><a href="{% url 'chapters:approach' last_topic_id %}">Kontynuuj naukę</a></h2>
      {% endif %}
    {% else %}
      <h2>
        <a href="{% url 'users:register' %}">Zarejestruj konto</a> aby rozpocząć naukę.
      </h2>
    {% endif %}
  </div>
  
  <div class="container_index">
    <div class="wrapper">
    <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Nazwa</th>
            <th>Punkty</th>
            <th>Poziom</th>
          </tr>
        </thead>
        <tbody>
        {% for user in users %}
          {% if user == request.user %}
            <tr style="background-color: orange">
            <td class="rank">{{ forloop.counter }}.</td>
            <td class="team">
              <img title="profile image" src="{{ user.profile.profile_image.url }}" class="avatar img-circle img-thumbnail" alt="avatar" height="25" width="25">
               {{ user.username }}</td>
            <td class="points">{{ user.profile.points }}</td>
            <td class="points">{{ user.profile.get_education_display }}</td>
          </tr>
          {% else %}
            <tr>
            <td class="rank">{{ forloop.counter }}.</td>
            <td class="team">
              <img title="profile image" src="{{ user.profile.profile_image.url }}" class="avatar img-circle img-thumbnail" alt="avatar" height="25" width="25">
               {{ user.username }}</td>
            <td class="points">{{ user.profile.points }}</td>
            <td class="points">{{ user.profile.skill_level }}</td>
          </tr>
          {% endif %}
        {% endfor %}
        </tbody>
    </table>
    </div>
  </div>
</div>
{% endblock content %}

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/kodowanie.html
{% extends 'chapters/baza.html' %}


{% block header %}
<div class="text-center mb-2">
  <h1>Code Mirror</h1>
</div>
{% endblock header %}



{% block content %}
<div class="d-flex flex-wrap justify-content-center">
  <div id="console" class="terminal">
    {% if res %}
        {{ res|linebreaks }}
    {% else %}
      <p>Tutaj pojawi się rezultat....</p>
      {% endif %}
    </div>

  <form action="{% url 'chapters:kodowanie' %}" method="post">
    <div class="approach_code_pomoc">
    {% csrf_token %}
    {{ form.as_p }}
      <script>
            var editor = CodeMirror.fromTextArea(document.getElementById('code'), {
                  mode: "python",
                  theme: "erlang-dark",
                  lineNumbers: true,
                  autoCloseBrackets: true,
                  lineWrapping: true
              });
              editor.setSize(null, 500);
        </script>
    </div>

    <button name="submit" class="btn btn-info float-left">Uruchom</button>
</form>
</div>
{% endblock content %}

{% block result %}
<div class="console">
  <header>
    <p>Terminal</p>
  </header>
  <div class="consolebody">
    <p >{{ res|linebreaks }}</p>
  </div>
</div>
{% endblock result %}

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/literatura.html
{% extends 'chapters/baza.html' %}
{% load static %}


{% block header %}
<div class="text-center mb-2">
  <h1>Literatura</h1>
</div>
{% endblock header %}


{% block content %}
  <ul class="list-group w-50 mx-auto">
    <li class="d-flex justify-content-between align-items-center mb-2" style="font-size: 20px;">
      Python Crash Course
      <div class="image-parent ml-2" >
          <a title= "Odwiedź świat książki"
             href="https://www.swiatksiazki.pl/python-crash-course-a-hands-on-project-based-introduction-to-programming-2nd-edition-6536742-ksiazka.html">
          <img src="{% static 'img/python-crash-course.jpg' %}" alt="quixote" height="150" width="100"></a>
      </div>
    </li>
    <li class="d-flex justify-content-between align-items-center mb-2" style="font-size: 20px;">
      Data science od podstaw: analiza danych w Pythonie
      <div class="image-parent ml-2">
        <a title= "Odwiedź świat książki"
           href="https://www.swiatksiazki.pl/data-science-od-podstaw-analiza-danych-w-pythonie-wydanie-2-6625783-ksiazka.html">
          <img src="{% static 'img/data-science.jpg' %}" alt="lay" height="150" width="100"></a>
    </div>
    </li>
  </ul>

{% endblock content %}

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">

  <a class="navbar-brand bg-image hover-zoom" href="{% url 'chapters:index' %}">
    <img title="home page" src="{% static 'img/python.png' %}" class="avatar img-circle img-thumbnail"
         alt="avatar" height="40" width="40">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chapters:chapters' %}">Rozdziały</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chapters:literatura' %}">Literatura</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chapters:kodowanie' %}">Kodowanie</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'chapters:pomoc' %}">Pomoc</a>
      </li>
    </ul>
    <ul class="navbar-nav justify-content-end">
        {% if user.is_authenticated %}
        <li class="text-center">
          <img title="profile image" src="{{ user.profile.profile_image.url }}" class="avatar img-circle img-thumbnail"
               alt="avatar" height="40" width="40">
        </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:auth_user_change' user.id %}">Witaj, {{ user.username }}</a>
      </li>
      
      <li class="nav-item">
        <a class="navbar-brand bg-image hover-zoom" href=#>{{ user.profile.points }}
          <img src="{% static 'img/points.png' %}" height="30" width="30">
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}">Wyloguj się</a>
      </li>
        {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">Zaloguj się</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:register' %}">Zarejestruj się</a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/pomoc.html
{% extends 'chapters/baza.html' %}
{% block header %}
<div class="text-center mb-2">
  <h1>Pomoc dla "{{ chapter.name }}"</h1>
</div>
{% endblock header %}

{% block content %}
<div class="code_pomoc">
    <textarea id="code_pomoc">
{{ chapter.pomoc_text }}
    </textarea>
</div>
<script>
        var editor = CodeMirror.fromTextArea(document.getElementById('code_pomoc'), {
            mode: "python",
            theme: "erlang-dark",
            lineNumbers: true,
            autoCloseBrackets: true,
            lineWrapping: true
        });
        editor.setSize(null, 550);
    </script>

{% endblock content %}

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/pomoc_list.html
{% extends 'chapters/baza.html' %}
{% load  chapters_extras %}
{% load  static %}

{% block header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'chapters:index' %}">Początek</a></li>
    <li class="breadcrumb-item active" aria-current="page">Pomoc</li>
  </ol>
</nav>
<div class="text-center mb-2">
  <h2>Pomoc dla rozadziałów:</h2>
</div>
{% endblock header %}

{% block content %}
<div class="d-flex flex-wrap justify-content-center">
{% for chapter in chapters %}
    <a href="{% url 'chapters:pomoc_chapter' chapter.id %}">
        <div class="card border-{% get_theme forloop.counter0 %} mx-2 my-2 float-left"
            style="width: 20rem;">
            <div class="card-header">{{ chapter.name }}</div>
            <div class="card-body">
            </div>
        </div>
    </a>
{% endfor %}
</div>
{% endblock content %}

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/test.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />



    <!-- 🚨 Notice this link -->


    <title>Toggle Bootstrap Theme</title>
  </head>
  <body>
    <nav class="navbar navbar-transparent">
      <!-- 🚨 Notice the toggleTheme() function -->
      <a
        href="javascript:void()"
        class="btn btn-outline-info btn-lg ml-auto font-weight-bold"
        id="theme-toggler"
        onclick="toggleTheme()"
      ></a>
    </nav>


  </body>
</html>

Aplikacja-do-nauki-Pythona/chapters/templates/chapters/topic.html
{% extends "chapters/baza.html" %}
{% load static %}
{% load  chapters_extras %}

{% block header %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Początek</a></li>
    <li class="breadcrumb-item">
      <a href="{% url 'chapters:chapters' %}">Rozdziały</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{{ chapter }}</li>
  </ol>
</nav>
  <h2>{{ chapter }}: </h2>
{% endblock header %}

{% block content %}
<div class="index_content">
  <div style="height: 500px; overflow-y:auto;">
    <table style="max-height: 500px; overflow: auto;">
      <tbody>
        {% for topic in topics %}
        <tr>
            <td class="team">
                <a href="{% url 'chapters:approach' topic.id %}">{{ forloop.counter }}. {{ topic }}</a>
                <span class="badge badge-primary badge-pill ml-2 float-right">
                {% get_topic_points_tag topic user %}
                    /{{ topic.points }}</span>
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
</div>
{% endblock content %}